# Generated by Django 2.1.7 on 2019-03-13 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190313_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_times',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
