# Generated by Django 2.1.7 on 2019-03-13 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_address_created_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='会員番号'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=30, verbose_name='建物名'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='市町村区'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=7, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='address',
            name='prefecture',
            field=models.CharField(blank=True, max_length=10, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='address',
            name='room',
            field=models.CharField(blank=True, max_length=10, verbose_name='部屋番号'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='丁番号'),
        ),
    ]
