# Generated by Django 2.1.7 on 2019-03-28 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190313_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tell',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
    ]
